% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by NFTOOL
% Created Fri Feb 06 21:19:48 EST 2015
%
% This script assumes these variables are defined:
%
%   inputs - input data.
%   targets - target data.

PIMA = csvread('../../data/pimatrain.csv');
inputs = PIMA(:, 1:end-1);
targets = PIMA(:, end);

% Create a Fitting Network
hiddenLayerSize = 10;
net = fitnet(hiddenLayerSize);


% Setup Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;


% Train the Network
[net,tr] = train(net,inputs',targets');

% Test the Network
outputs = net(inputs');
errors = gsubtract(targets',outputs);
performance = perform(net,targets',outputs);

% View the Network
% view(net)

y = net(inputs');
% Calculating the mean squared error
mse_calc = (sum((y-targets').^2))/length(y)
pred = round(y);
pred = arrayfun(@(x) cust_ceil(x), pred);
confusion(pred, targets')

% compare against the testing
PIMATEST = csvread('../../data/pimatest.csv');
inputs_test = PIMATEST(:, 1:end-1);
targets_test = PIMATEST(:, end);

y = net(inputs_test');
% Calculating the mean squared error
mse_calc = (sum((y-targets_test').^2))/length(y)
pred = round(y);
pred = arrayfun(@(x) cust_ceil(x), pred);
confusionmat(pred, targets_test');
confusion(pred, targets_test')



% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, plotfit(net,inputs,targets)
%figure, plotregression(targets,outputs)
%figure, ploterrhist(errors)
